# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
  # you may remove this if you don't use vgo
  #    - go mod vendor
  # you may remove this if you don't need go generate
#    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor
    goos:
      - darwin
      - linux
      - freebsd
      - windows
    goarch:
      - amd64
      - arm64

checksum:
  name_template: 'checksums.txt'
sign:
  artifacts: checksum
snapshot:
  name_template: "{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brew:
  # Repository to push the tap to.
  github:
    owner: lfaoro
    name: tap

  # Git author used to commit to the repository.
  # Defaults are shown.
  commit_author:
    name: Leonardo Faoro
    email: lfaoro@gmail.com

  # Your app's homepage.
  # Default is empty.
  homepage: "https://github.com/lfaoro"

  # Your app's description.
  # Default is empty.
  description: "a geeky & friendly way to simply encrypt locally & share."

  # Setting this will prevent goreleaser to actually try to commit the updated
  # formula - instead, the formula file will be stored on the dist folder only,
  # leaving the responsibility of publishing it to the user.
  # If set to auto, the release will not be uploaded to the homebrew tap
  # in case there is an indicator for prerelease in the tag e.g. v1.0.0-rc1
  # Default is false.
  skip_upload: false

  # So you can `brew test` your formula.
  # Default is empty.
  test: |
    system "#{bin}/ncrypt --version"